name: flutter_generate
description: A sample command-line application which can create .dart files to determine a structure
version: 0.1.1
homepage: https://github.com/onatcipli/flutter_generate
author: Onat Çipli <ciplionat35@gmail.com>

environment:
  sdk: '>=2.3.0-dev.0.5 <3.0.0'

executables:
  flutter_generate:

dependencies:
  recase: ^2.0.1
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
